import os

from collections import Counter
from datetime import datetime


class ReportGenerator:

    @staticmethod
    def _severity_badge(severity: str):

        severity_mapping = {
            "critical": "🔴 CRITICAL",
            "warning": "🟠 WARNING",
            "info": "🔵 INFO"
        }

        return severity_mapping.get(
            severity.lower(),
            severity.upper()
        )

    @staticmethod
    def generate(anomalies, output_path):

        output_dir = os.path.dirname(output_path)

        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)

        total_anomalies = len(anomalies)

        unique_batches = len(set(
            anomaly["batch_id"]
            for anomaly in anomalies
        ))

        anomaly_type_counter = Counter(
            anomaly["anomaly_type"]
            for anomaly in anomalies
        )

        severity_counter = Counter(
            anomaly["severity"]
            for anomaly in anomalies
        )

        markdown_lines = []

        # =========================
        # Header
        # =========================

        markdown_lines.extend([
            "# 🚨 Pipeline Anomaly Detection Report",
            "",
            f"Generated At: `{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}`",
            ""
        ])

        # =========================
        # Summary
        # =========================

        markdown_lines.extend([
            "## 📊 Summary",
            "",
            f"- Total Anomalies: **{total_anomalies}**",
            f"- Affected Batches: **{unique_batches}**",
            ""
        ])

        # =========================
        # Anomaly Type Distribution
        # =========================

        markdown_lines.extend([
            "## 📌 Anomaly Type Distribution",
            "",
            "| Anomaly Type | Count |",
            "|---|---:|"
        ])

        for anomaly_type, count in anomaly_type_counter.items():

            markdown_lines.append(
                f"| {anomaly_type} | {count} |"
            )

        markdown_lines.append("")

        # =========================
        # Severity Distribution
        # =========================

        markdown_lines.extend([
            "## ⚠️ Severity Distribution",
            "",
            "| Severity | Count |",
            "|---|---:|"
        ])

        for severity, count in severity_counter.items():

            markdown_lines.append(
                f"| {ReportGenerator._severity_badge(severity)} | {count} |"
            )

        markdown_lines.append("")

        # =========================
        # Detailed Table
        # =========================

        markdown_lines.extend([
            "## 🧾 Anomaly Details",
            "",
            "| Batch ID | Type | Metric | Actual | Expected Range | Trigger Condition | Score | Severity |",
            "|---|---|---|---:|---|---:|---|---|"
        ])

        for anomaly in anomalies:

            markdown_lines.append(
                "| "
                f"{anomaly['batch_id']} | "
                f"{anomaly['anomaly_type']} | "
                f"{anomaly['metric_name']} | "
                f"{anomaly['actual_value']:.4f} | "
                f"{anomaly['expected_range']} | "
                f"{anomaly['trigger_condition'].replace('|', '\\|')} | "
                f"{anomaly['deviation_score']:.4f} | "
                f"{ReportGenerator._severity_badge(anomaly['severity'])} |"
            )

        markdown_lines.append("")

        # =========================
        # Footer
        # =========================

        markdown_lines.extend([
            "---",
            "",
            "Generated by Pipeline Anomaly Detection System",
            ""
        ])

        with open(output_path, "w", encoding="utf-8") as file:

            file.write("\n".join(markdown_lines))

        print(
            f"Markdown anomaly report generated: {output_path}"
        )